os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh Scripts/install-mysql-5.7.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql.server start; fi
  - mysql -uroot -e 'CREATE DATABASE swift_knex_test;'

install:
  - source Scripts/install-swift.sh

script:
  - swift build
  - swift build -c release
  - swift test
